"""add trigger type to indexing jobs

Revision ID: ce7911ec97d4
Revises: fbfc24ae176a
Create Date: 2026-09-06 18:22:17.401786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce7911ec97d4'
down_revision: Union[str, Sequence[str], None] = 'fbfc24ae176a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indexing_jobs', sa.Column('trigger_type', sa.String(length=100), nullable=False))
    op.add_column('pull_requests', sa.Column('base_commit_sha', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pull_requests', 'base_commit_sha')
    op.drop_column('indexing_jobs', 'trigger_type')
    # ### end Alembic commands ###
