"""create pull requests table

Revision ID: de95d634a967
Revises: 2397677f7680
Create Date: 2026-08-14 15:54:16.707819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de95d634a967'
down_revision: Union[str, Sequence[str], None] = '2397677f7680'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pull_requests', 'github_pr_number',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.create_unique_constraint('uq_repository_pr', 'pull_requests', ['repository_id', 'github_pr_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_repository_pr', 'pull_requests', type_='unique')
    op.alter_column('pull_requests', 'github_pr_number',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
